# 一、series学习

## 1.series的创建

In [1]:
from os import name

import numpy as np
# series的创建
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# 自定义索引
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
# 定义name
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],name = '月份')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64

In [6]:
# 通过字典形式创建
s = pd.Series({'a':1,'b':2,'c':3,'d':4} ,name = '月份' )
print(s)
s1 = pd.Series(s,index=['a','b'])
print(s1)

a    1
b    2
c    3
d    4
Name: 月份, dtype: int64
a    1
b    2
Name: 月份, dtype: int64

## 2.Series的属性

In [17]:
'''
index:Series的索引对象
values:Series的值
dtype或dtypes:Series的元素类型
shape:Series的形状
ndim:Series的维度
size:Series的元素个数
name:Series的名称
Loc[] 显式索引，按标签索引或切片
iloc[] 隐式索引，按位置索引或切片
at[] 使用标签访问单个元素
iat[] 使用位置访问单个元素
'''
print(s)
print(s.index)
print(s.values)
print(s.shape)
print(s.ndim)
print(s.size)
print(s.name)
print(s.loc['a']) #显式索引，支持切片
print(s.iloc[1]) #隐式索引，支持切片
print(s.at['a']) # 不支持切片
print(s.iat[0])

a    1
b    2
c    3
d    4
Name: 月份, dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='str')
[1 2 3 4]
(4,)
1
4
月份
1
2
1
1

In [25]:
# 访问数据
print(s['a'])
print(s[s<3])
s = pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'],name='月份')
print(s)
print(s.head()) #打印前五行
print(s.head(2)) #打印前2行
print(s.tail()) # 打印末尾五行
print(s.tail(2)) # 打印末尾2行

1
a    1
b    2
Name: 月份, dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: 月份, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64
a    1
b    2
Name: 月份, dtype: int64
e    5
f    6
g    7
h    8
i    9
Name: 月份, dtype: int64
h    8
i    9
Name: 月份, dtype: int64

In [32]:
# 常见函数
s = pd.Series([1,np.nan,3,None,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'],name='月份')
print(s)

a    1.0
b    NaN
c    3.0
d    NaN
e    5.0
f    6.0
g    7.0
h    8.0
i    9.0
Name: 月份, dtype: float64

In [33]:
s.head()

a    1.0
b    NaN
c    3.0
d    NaN
e    5.0
Name: 月份, dtype: float64

In [34]:
# 查看所有的描述信息
s.describe()  # count()自动忽略缺失值

count    7.000000
mean     5.571429
std      2.819997
min      1.000000
25%      4.000000
50%      6.000000
75%      7.500000
max      9.000000
Name: 月份, dtype: float64

In [36]:
# 获取元素个数
print(s.count())

7

In [38]:
# 获取索引
print(s.keys())  # 方法
print(s.index)   # 属性

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='str')

In [41]:
# 判断元素是否为缺失值
s.isna()

a    False
b     True
c    False
d     True
e    False
f    False
g    False
h    False
i    False
Name: 月份, dtype: bool

In [44]:
# 判断元素是否在参数集合中
print(s.isin([4,6]))

a    False
b    False
c    False
d    False
e    False
f     True
g    False
h    False
i    False
Name: 月份, dtype: bool

In [47]:
print(s.median())
print(s.quantile(0.5)) # 括号中元素区间范围（0，1）

6.0
9.0

In [49]:
# 众数
print(s.mode())

0    1.0
1    3.0
2    5.0
3    6.0
4    7.0
5    8.0
6    9.0
Name: 月份, dtype: float64

In [50]:
# 出现的次数
print(s.value_counts())

月份
1.0    1
3.0    1
5.0    1
6.0    1
7.0    1
8.0    1
9.0    1
Name: count, dtype: int64

In [54]:
# 去重
print(s.drop_duplicates())
print(s.unique())
# 去重之后的元素个数
print(s.nunique())

a    1.0
b    NaN
c    3.0
e    5.0
f    6.0
g    7.0
h    8.0
i    9.0
Name: 月份, dtype: float64
[ 1. nan  3.  5.  6.  7.  8.  9.]
7

In [56]:
# 排序  值、索引
print(s.sort_index())
print(s.sort_values())

a    1.0
b    NaN
c    3.0
d    NaN
e    5.0
f    6.0
g    7.0
h    8.0
i    9.0
Name: 月份, dtype: float64
a    1.0
c    3.0
e    5.0
f    6.0
g    7.0
h    8.0
i    9.0
b    NaN
d    NaN
Name: 月份, dtype: float64

## 2.案例练习

In [58]:
text_data = [
    "大模型RAG可以实现私有知识库问答",
    "向量数据库负责文本相似度检索",
    "LangChain提供文档分割与检索链工具",
    "Ollama支持本地离线部署开源大模型",
    "FastAPI可以将RAG封装成接口服务"
]
text_series = pd .Series(text_data)
# 构建Series
text_series = pd.Series(text_data, name="知识库文本")
print("=== 案例1：基础文本Series ===")
print(text_series)
print("-" * 80)

# ======================
# 案例2：自定义索引Series（给每条文本分配文档ID）
# ======================
doc_ids = ["doc001", "doc002", "doc003", "doc004", "doc005"]
index_series = pd.Series(text_data, index=doc_ids, name="带文档ID的文本")
print("=== 案例2：自定义索引Series ===")
print(index_series)
print("通过文档ID doc003取值：", index_series["doc003"])
print("-" * 80)

# ======================
# 案例3：Series基础取值、切片（筛选知识库片段）
# ======================
print("=== 案例3：切片与取值操作 ===")
# 取前2条文本
print("前两条文本：")
print(index_series[:2])
# 条件筛选：包含RAG关键词的文本
rag_text = index_series[index_series.str.contains("RAG")]
print("\n包含RAG关键词的文本：")
print(rag_text)
print("-" * 80)

# ======================
# 案例4：Series文本清洗（RAG核心需求：文本预处理）
# ======================
dirty_text = [
    "  向量数据库，用于文本检索！！  ",
    "LANGCHAIN 实现检索问答链##",
    "  Ollama本地大模型部署  ",
    "FAISS 轻量级向量库，适合本地项目！"
]
dirty_series = pd.Series(dirty_text, name="待清洗文本")
print("=== 案例4：文本清洗实战 ===")
print("清洗前：")
print(dirty_series)

# 清洗步骤：去空格、转小写、去除特殊符号
clean_series = dirty_series.str.strip()  # 去除首尾空格
clean_series = clean_series.str.lower()  # 全部转为小写
clean_series = clean_series.str.replace(r"[#！]", "", regex=True)  # 去除符号
print("\n清洗后：")
print(clean_series)

=== 案例1：基础文本Series ===
0        大模型RAG可以实现私有知识库问答
1           向量数据库负责文本相似度检索
2    LangChain提供文档分割与检索链工具
3      Ollama支持本地离线部署开源大模型
4     FastAPI可以将RAG封装成接口服务
Name: 知识库文本, dtype: str
--------------------------------------------------------------------------------
=== 案例2：自定义索引Series ===
doc001        大模型RAG可以实现私有知识库问答
doc002           向量数据库负责文本相似度检索
doc003    LangChain提供文档分割与检索链工具
doc004      Ollama支持本地离线部署开源大模型
doc005     FastAPI可以将RAG封装成接口服务
Name: 带文档ID的文本, dtype: str
通过文档ID doc003取值： LangChain提供文档分割与检索链工具
--------------------------------------------------------------------------------
=== 案例3：切片与取值操作 ===
前两条文本：
doc001    大模型RAG可以实现私有知识库问答
doc002       向量数据库负责文本相似度检索
Name: 带文档ID的文本, dtype: str

包含RAG关键词的文本：
doc001       大模型RAG可以实现私有知识库问答
doc005    FastAPI可以将RAG封装成接口服务
Name: 带文档ID的文本, dtype: str
--------------------------------------------------------------------------------
=== 案例4：文本清洗实战 ===
清洗前：
0        向量数据库，用于文本检索！！
1     LANGCHAIN 实现检索问答链##
2         Ollama本地大模型部署
3    FAISS 轻量级向量库，适合本地项目！
Name: 待清洗文本, dtype: str

清洗后：
0           向量数据库，用于文本检索
1      langchain 实现检索问答链
2          ollama本地大模型部署
3    faiss 轻量级向量库，适合本地项目
Name: 待清洗文本, dtype: str

# 二、Dataframe学习

## 1.dataframe的创建

In [61]:
# dataframe的创建
# 通过series来创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({'第一列':s1,'第二列':s2})
print(df)
type(df['第一列'])

   第一列  第二列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

pandas.Series

In [66]:
# 通过字典来创建
df = pd.DataFrame(
    {
        'id':[1,2,3,4,5],
        'name':['a','b','c','d','e'],
    },index=[1,2,3,4,5],columns=['name','id']
)
print(df)

  name  id
1    a   1
2    b   2
3    c   3
4    d   4
5    e   5

## 2.dataframe的属性

In [ ]:
'''
index: DataFrame的行索引
columns:DataFrame的列标签
values:DataFrame的值
dtypes:DataFrame的元素类型
shape: DataFrame的形状
ndim:  DataFrame的维度
size:  DataFrame的元素个数
Loc[] 显式索引，按行列索引或切片
iloc[] 隐式索引，按行行列位置索引或切片
at[] 使用行列标签访问单个元素
iat[] 使用行列位置访问单个元素
T 行列转置
'''

In [70]:
print(df.index)
print(df.values)
print(df.dtypes)
print(df.shape)
print(df.ndim)
print(df.size)
print(df.columns)

Index([1, 2, 3, 4, 5], dtype='int64')
[['a' 1]
 ['b' 2]
 ['c' 3]
 ['d' 4]
 ['e' 5]]
name      str
id      int64
dtype: object
(5, 2)
2
10
Index(['name', 'id'], dtype='str')

In [83]:
print(df.loc[0:2])
print(df.loc[3])
print(df.iloc[2])
print(df.iloc[0:2])
print(df.loc[:,'name']) # 取列 [:] 全取

  name  id
1    a   1
2    b   2
name    c
id      3
Name: 3, dtype: object
name    c
id      3
Name: 3, dtype: object
  name  id
1    a   1
2    b   2
1    a
2    b
3    c
4    d
5    e
Name: name, dtype: str

In [90]:
print(df.at[1,'name'])
print(df.iat[0,0])

a
a

In [93]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))

1    a
2    b
3    c
4    d
5    e
Name: name, dtype: str
<class 'pandas.Series'>
1    a
2    b
3    c
4    d
5    e
Name: name, dtype: str
<class 'pandas.Series'>

In [95]:
# 查看部分数据
print(df.head(2))
print(df.tail(2))

  name  id
1    a   1
2    b   2
  name  id
4    d   4
5    e   5

In [101]:
# bool索引
df[df.id==1]

In [103]:
# 随机抽样
df.sample(2)

  name  id
5    e   1
4    d   1

## 3.dataframe常见方法

In [104]:
print(df.count()) # 每一列非缺失值的个数

name    5
id      5
dtype: int64

In [106]:
print(df.value_counts()) # 重复出现的次数统计

name  id
a     1     1
b     1     1
c     1     1
d     1     1
e     1     1
Name: count, dtype: int64

In [107]:
print(df.drop_duplicates()) # 删除重复值

  name  id
1    a   1
2    b   1
3    c   1
4    d   1
5    e   1

In [109]:
print(df.duplicated()) # 检查是否重复

1    False
2    False
3    False
4    False
5    False
dtype: bool

In [112]:
print(df.replace('a','易')) # 替换

  name  id
1    易   1
2    b   1
3    c   1
4    d   1
5    e   1

In [122]:
df
df.cumsum()

    name  id
1      a   1
2     ab   2
3    abc   3
4   abcd   4
5  abcde   5

In [132]:
df.sort_index()
df.sort_values(by=['name','id'],ascending=[False,True])   # by后面接排序对象，ascending是否从高到低排序

  name  id
5    e   1
4    d   1
3    c   1
2    b   1
1    a   1

In [135]:
df.nlargest(2,columns=['id'])
df.nsmallest(2,columns=['id'])

  name  id
1    a   1
2    b   1

## 4.案例练习

In [136]:
import pandas as pd

# 模拟私有知识库问答数据
data = {
    "doc_id": ["doc001", "doc002", "doc003", "doc004", "doc005", "doc006"],
    "category": ["RAG基础", "向量库", "大模型部署", "RAG基础", "向量库", "大模型部署"],
    "question": [
        "什么是RAG检索增强生成？",
        "FAISS和Chroma有什么区别？",
        "Ollama怎么本地运行Llama3？",
        "RAG可以解决大模型幻觉吗？",
        "向量数据库的相似度检索原理？",
        "如何限制Ollama占用显存？"
    ],
    "answer": [
        "RAG通过检索外部知识库再交给大模型生成答案，减少幻觉。",
        "FAISS轻量适合本地；Chroma开箱即用，自带持久化存储。",
        "安装Ollama后终端执行 ollama run llama3 即可本地调用。",
        "可以，RAG让模型基于真实文档回答，凭空编造内容大幅减少。",
        "文本转为向量，通过余弦距离计算向量相似度，匹配相似文档。",
        "启动模型时添加参数 num_gpu 限制显卡显存分配。"
    ],
    "char_length": [36, 42, 39, 35, 41, 38]
}

# 创建DataFrame
df = pd.DataFrame(data)
print("完整知识库问答表格：")
df

完整知识库问答表格：

,doc_id,category,question,answer,char_length
0,doc001,RAG基础,什么是RAG检索增强生成？,RAG通过检索外部知识库再交给大模型生成答案，减少幻觉。,36
1,doc002,向量库,FAISS和Chroma有什么区别？,FAISS轻量适合本地；Chroma开箱即用，自带持久化存储。,42
2,doc003,大模型部署,Ollama怎么本地运行Llama3？,安装Ollama后终端执行 ollama run llama3 即可本地调用。,39
3,doc004,RAG基础,RAG可以解决大模型幻觉吗？,可以，RAG让模型基于真实文档回答，凭空编造内容大幅减少。,35
4,doc005,向量库,向量数据库的相似度检索原理？,文本转为向量，通过余弦距离计算向量相似度，匹配相似文档。,41
5,doc006,大模型部署,如何限制Ollama占用显存？,启动模型时添加参数 num_gpu 限制显卡显存分配。,38

In [142]:
# 1. 查看所有RAG基础分类的数据
rag_base = df[df["category"] == "RAG基础"]
print("==== RAG基础类问答 ====")
display(rag_base)

# 2. 多条件筛选：向量库分类 + 字符长度大于40
vector_long = df[(df["category"] == "向量库") & (df["char_length"] > 40)]
print("\n==== 向量库长文本问答 ====")
display(vector_long)

# 3. 只提取问题、答案两列
qa_df = df[["question", "answer"]]
print("\n==== 仅问答字段 ====")
display(qa_df)

==== RAG基础类问答 ====

   doc_id category        question                         answer  char_length
0  doc001    RAG基础   什么是RAG检索增强生成？   RAG通过检索外部知识库再交给大模型生成答案，减少幻觉。           36
3  doc004    RAG基础  RAG可以解决大模型幻觉吗？  可以，RAG让模型基于真实文档回答，凭空编造内容大幅减少。           35

==== 向量库长文本问答 ====

,doc_id,category,question,answer,char_length
1,doc002,向量库,FAISS和Chroma有什么区别？,FAISS轻量适合本地；Chroma开箱即用，自带持久化存储。,42
4,doc005,向量库,向量数据库的相似度检索原理？,文本转为向量，通过余弦距离计算向量相似度，匹配相似文档。,41

==== 仅问答字段 ====

              question                                   answer
0        什么是RAG检索增强生成？             RAG通过检索外部知识库再交给大模型生成答案，减少幻觉。
1   FAISS和Chroma有什么区别？          FAISS轻量适合本地；Chroma开箱即用，自带持久化存储。
2  Ollama怎么本地运行Llama3？  安装Ollama后终端执行 ollama run llama3 即可本地调用。
3       RAG可以解决大模型幻觉吗？            可以，RAG让模型基于真实文档回答，凭空编造内容大幅减少。
4       向量数据库的相似度检索原理？             文本转为向量，通过余弦距离计算向量相似度，匹配相似文档。
5      如何限制Ollama占用显存？              启动模型时添加参数 num_gpu 限制显卡显存分配。

In [138]:
# 制造带缺失值的数据（模拟爬取/导入空白文档）
dirty_data = {
    "doc_id": ["doc007", "doc008", "doc009"],
    "category": ["向量库", None, "RAG基础"],
    "question": ["Chroma如何持久化数据？", "本地RAG怎么搭建？", ""],
    "answer": ["使用persist_directory参数保存向量文件", "分文档加载、向量化、检索三步", None]
}
dirty_df = pd.DataFrame(dirty_data)
print("清洗前（存在空值、空白文本）：")
display(dirty_df)

# 清洗步骤
# 1. 空白question替换为NaN
dirty_df["question"] = dirty_df["question"].replace("", pd.NA)
# 2. 删除answer为空的无效数据
clean_df = dirty_df.dropna(subset=["answer"])
# 3. 分类缺失值填充为"未分类"
clean_df["category"] = clean_df["category"].fillna("未分类")

print("\n清洗完成后的有效知识库数据：")
display(clean_df)

清洗前（存在空值、空白文本）：

   doc_id category        question                       answer
0  doc007      向量库  Chroma如何持久化数据？  使用persist_directory参数保存向量文件
1  doc008      NaN      本地RAG怎么搭建？               分文档加载、向量化、检索三步
2  doc009    RAG基础                                          NaN

清洗完成后的有效知识库数据：

   doc_id category        question                       answer
0  doc007      向量库  Chroma如何持久化数据？  使用persist_directory参数保存向量文件
1  doc008      未分类      本地RAG怎么搭建？               分文档加载、向量化、检索三步

In [139]:
# 按文档分类分组统计
group_result = df.groupby("category").agg(
    文档数量=("doc_id", "count"),
    平均文本长度=("char_length", "mean")
).round(2)

print("各知识库分类统计汇总：")
display(group_result)

各知识库分类统计汇总：

          文档数量  平均文本长度
category
RAG基础        2    35.5
向量库          2    41.5
大模型部署        2    38.5

In [140]:
# 合并原始干净数据和清洗数据
full_kb = pd.concat([df, clean_df], ignore_index=True)
# 导出csv文件，保存到本地，后续读取做向量入库
full_kb.to_csv("rag_knowledge_base.csv", index=False, encoding="utf-8-sig")
print("知识库已导出为 rag_knowledge_base.csv")

# 读取csv验证
load_df = pd.read_csv("rag_knowledge_base.csv", encoding="utf-8-sig")
print("\n读取导出后的文件：")
display(load_df.head())

知识库已导出为 rag_knowledge_base.csv

读取导出后的文件：

,doc_id,category,question,answer,char_length
0,doc001,RAG基础,什么是RAG检索增强生成？,RAG通过检索外部知识库再交给大模型生成答案，减少幻觉。,36.0
1,doc002,向量库,FAISS和Chroma有什么区别？,FAISS轻量适合本地；Chroma开箱即用，自带持久化存储。,42.0
2,doc003,大模型部署,Ollama怎么本地运行Llama3？,安装Ollama后终端执行 ollama run llama3 即可本地调用。,39.0
3,doc004,RAG基础,RAG可以解决大模型幻觉吗？,可以，RAG让模型基于真实文档回答，凭空编造内容大幅减少。,35.0
4,doc005,向量库,向量数据库的相似度检索原理？,文本转为向量，通过余弦距离计算向量相似度，匹配相似文档。,41.0