In [4]:
import csv

# 数据的导入
import numpy as np
import pandas as pd
from IPython.display import display



df = pd.read_csv('../data/employees.csv')
display(df)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [206]:
type(df)
df = df.tail()
df.to_csv('data/new.csv')

In [207]:
# json
df = pd.read_json('../data/data1.json')
display(df)
type(df)

   id name  age
0   1   张三   25
1   2   李四   30
2   3   王五   28

pandas.DataFrame

In [208]:
# json文件的处理
import json
f = open('../data/test.json', 'r', encoding='utf-8')
data = json.load(f)
print(data)
df = pd.DataFrame(data['users'])
print(df)

{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}
   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [209]:
# 缺失值的处理
# nan: not a number
s = pd.Series([1,2,np.nan,None,pd.NA])
s
df = pd.DataFrame([[1,2,np.nan],[6,2,5],[None,7,6]],columns=['第1列','第2列','第3列'],)
print(df)
# 查看是否是缺失值
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum()) #查看缺失值的个数
print(df.isna().sum(axis=0)) #查看缺失值的个数
print(s.isna().sum())

   第1列  第2列  第3列
0  1.0    2  NaN
1  6.0    2  5.0
2  NaN    7  6.0
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第1列    第2列    第3列
0  False  False   True
1  False  False  False
2   True  False  False
     第1列    第2列    第3列
0  False  False   True
1  False  False  False
2   True  False  False
第1列    1
第2列    0
第3列    1
dtype: int64
第1列    1
第2列    0
第3列    1
dtype: int64
3

In [210]:
# 剔除缺失值
print(s.dropna())
print('-'*50)
print(df.dropna()) # 剔除一整条的记录
print(df.dropna(how='all')) # 如果所有的值都是缺失值，剔除这一行
print(df.dropna(thresh=3)) # 如果至少有n个值不是缺失值，保留这一行
print(df.dropna(axis=1)) # 剔除一整列的记录
print(df.dropna(subset=['第1列'])) # 如果某列有缺失值，则删除这一行

0    1
1    2
dtype: object
--------------------------------------------------
   第1列  第2列  第3列
1  6.0    2  5.0
   第1列  第2列  第3列
0  1.0    2  NaN
1  6.0    2  5.0
2  NaN    7  6.0
   第1列  第2列  第3列
1  6.0    2  5.0
   第2列
0    2
1    2
2    7
   第1列  第2列  第3列
0  1.0    2  NaN
1  6.0    2  5.0

In [211]:
# 填充缺失值
df = pd.read_csv('../data/weather_withna.csv')
display(df.tail())
df.isna().sum(axis=0)
print(df.fillna({'temp_max':20}).tail()) # 使用字典来填充
print(df.fillna(df[['wind']].mean().tail()))
print(df.ffill().tail()) #用前面的相邻值填充
print(df.bfill().tail()) #用后面的相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700000  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500000     rain
2     2012-01-03            0.8      11.7       7.2  2.300000     rain
3     2012-01-04           20.3      12.2       5.6  4.700000     rain
4     2012-01-05            1.3       8.9       2.8  6.100000     rain
...          ...            ...       ...       ...       ...      ...
1456  2015-12-27            NaN       NaN       NaN  3.242055      NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055      NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055      NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055      NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000     rain

[1461 rows x 6 columns]
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [212]:
data ={'name':['alice','alice','bob','alice','jack','bob'],
    'age':[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA']}
df = pd.DataFrame(data)
display(df)

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [213]:
df.duplicated() # 一整条记录都是一样的，标记为重复，返回True

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [214]:
df.drop_duplicates() #删除重复值

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
4   jack   35   SF

In [215]:
df.drop_duplicates(subset=['name']) #删除指定列的重复值
df.drop_duplicates(subset=['name'],keep='last') #删除指定列的重复值,并记录最新值

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [216]:
# 数据类型的转换
df = pd.read_csv('../data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [217]:
df['age'] = df['age'].astype('int16') # 转换类型
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [218]:
df['gender'] = df['gender'].astype('category') #分类，可提效
df.dtypes
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [219]:
df['is_male'] = df['gender'].map({'Male':True,'Female':False}) # map做映射
df.is_male
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,is_male
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN,True
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN,False
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN,True
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN,True
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea,False
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia,False
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia,False
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea,False
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN,True

In [220]:
# 数据变形
data = {
    'ID':[1,2],
    'name':['alice','bob'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
df.T
df
# 宽表转化为长表
df2 =  pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')
# 长表转宽表
print(pd.pivot(df2,index=['ID','name'],columns='科目',values='分数'))
print('-'*30)
print(pd.pivot(df2,index=['ID','name'],columns='分数',values='科目'))

科目        English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89
------------------------------
分数          85       88       89    90       92       95
ID name
1  alice   NaN  English      NaN  Math      NaN  Science
2  bob    Math      NaN  Science   NaN  English      NaN

In [221]:
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
# 分列

df[['first','last']] = df['name'].str.split(' ' , expand=True)
df

   ID         name  Math  English  Science  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith

In [222]:
df = pd.read_csv('../data/sleep.csv')
df = df[['person_id','blood_pressure']]
df[['high','low']]=df['blood_pressure'].str.split('/',expand=True)
df['high']=df['high'].astype('int16')
df['low']=df['low'].astype('int16')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high            400 non-null    int16
 3   low             400 non-null    int16
dtypes: int16(2), int64(1), str(1)
memory usage: 7.9 KB

In [223]:
#分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数（）
df = pd.read_csv('../data/employees.csv')
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [224]:
df = df.dropna(subset=['department_id'])
print(df['department_id'].isna().sum())
df['department_id'] = df['department_id'].astype('int16')
df

0

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110

In [225]:
# 计算不同部门的平均薪资
df.groupby('department_id').groups # 查看分组
df.groupby('department_id').get_group(20) # 查看具体的某个分组
df.groupby('department_id')[['salary']].mean().round(2).reset_index().sort_values('salary', ascending=False)

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [226]:
# 计算不同部门不同岗位人的平均薪资
df.groupby(['department_id','job_id'])[['salary']].mean().sort_values('salary', ascending=False).reset_index().round(1)

    department_id      job_id   salary
0              90     AD_PRES  24000.0
1              90       AD_VP  17000.0
2              20      MK_MAN  13000.0
3              80      SA_MAN  12200.0
4             100      FI_MGR  12000.0
5             110      AC_MGR  12000.0
6              30      PU_MAN  11000.0
7              70      PR_REP  10000.0
8              80      SA_REP   8396.6
9             110  AC_ACCOUNT   8300.0
10            100  FI_ACCOUNT   7920.0
11             50      ST_MAN   7280.0
12             40      HR_REP   6500.0
13             20      MK_REP   6000.0
14             60     IT_PROG   5760.0
15             10     AD_ASST   4400.0
16             50    SH_CLERK   3215.0
17             50    ST_CLERK   2785.0
18             30    PU_CLERK   2780.0

## 案例练习

In [84]:
import pandas as pd
df = pd.read_csv('../data/dirty_data.csv')
df

   doc_id category         question               answer
0  doc001      RAG      什么是RAG？      RAG全称检索增强生成，缓解大模型幻觉
1  doc002      向量库  Chroma和FAISS区别？                  NaN
2  doc003      RAG              NaN   RAG需要先对文档文本切分，再向量化
3  doc004   Ollama    Ollama怎么限制显存？  启动模型设置num_gpu参数！！##
4  doc005      向量库         向量相似度原理？                  NaN
5  doc006      RAG    RAG有哪些缺点？          知识库更新时需要重新向量化文档
6  doc007      NaN   Langchain作用是什么        用于快速搭建大模型应用链路

#### 1.首尾空格清除 2.空字符串替换为缺失值 3.answer中清除多余特殊符号 4.删除answer为空的无效回答 5.缺失分类填充为未分类

In [95]:
df['question'] = df['question'].str.strip()
df['answer'] = df['answer'].str.replace(r'[！!#]','',regex=True)
df['question'] = df['question'].replace('',pd.NA)
df

   doc_id category         question               answer
0  doc001      RAG          什么是RAG？  RAG全称检索增强生成，缓解大模型幻觉
1  doc002      向量库  Chroma和FAISS区别？                  NaN
2  doc003      RAG              NaN   RAG需要先对文档文本切分，再向量化
3  doc004   Ollama    Ollama怎么限制显存？      启动模型设置num_gpu参数
4  doc005      向量库         向量相似度原理？                  NaN
5  doc006      RAG        RAG有哪些缺点？      知识库更新时需要重新向量化文档
6  doc007      NaN   Langchain作用是什么        用于快速搭建大模型应用链路

In [99]:
df = df.dropna(subset= ["answer"])
df

   doc_id category        question               answer
0  doc001      RAG         什么是RAG？  RAG全称检索增强生成，缓解大模型幻觉
2  doc003      RAG             NaN   RAG需要先对文档文本切分，再向量化
3  doc004   Ollama   Ollama怎么限制显存？      启动模型设置num_gpu参数
5  doc006      RAG       RAG有哪些缺点？      知识库更新时需要重新向量化文档
6  doc007      NaN  Langchain作用是什么        用于快速搭建大模型应用链路

In [101]:
df["category"]=df["category"].fillna("未分类")
df

   doc_id category        question               answer
0  doc001      RAG         什么是RAG？  RAG全称检索增强生成，缓解大模型幻觉
2  doc003      RAG             NaN   RAG需要先对文档文本切分，再向量化
3  doc004   Ollama   Ollama怎么限制显存？      启动模型设置num_gpu参数
5  doc006      RAG       RAG有哪些缺点？      知识库更新时需要重新向量化文档
6  doc007      未分类  Langchain作用是什么        用于快速搭建大模型应用链路

In [103]:
df["answer_length"]=df["answer"].str.len()
df

   doc_id category        question               answer  answer_length
0  doc001      RAG         什么是RAG？  RAG全称检索增强生成，缓解大模型幻觉             19
2  doc003      RAG             NaN   RAG需要先对文档文本切分，再向量化             18
3  doc004   Ollama   Ollama怎么限制显存？      启动模型设置num_gpu参数             15
5  doc006      RAG       RAG有哪些缺点？      知识库更新时需要重新向量化文档             15
6  doc007      未分类  Langchain作用是什么        用于快速搭建大模型应用链路             13

In [104]:
df_rag = df[df['category']=='RAG']
df_rag

   doc_id category   question               answer  answer_length
0  doc001      RAG    什么是RAG？  RAG全称检索增强生成，缓解大模型幻觉             19
2  doc003      RAG        NaN   RAG需要先对文档文本切分，再向量化             18
5  doc006      RAG  RAG有哪些缺点？      知识库更新时需要重新向量化文档             15

# pandas命令总结

## 1.数据创建与查看

In [ ]:
# 1. 创建Series
s = pd.Series([1,2,3], name="文本")
# 2. 创建DataFrame
df = pd.DataFrame('字典列表')

# 3. 查看基础信息
df.head()         # 前5行
df.info()         # 数据类型、缺失值统计
df.shape          # (行数,列数)
df.columns        # 获取所有列名

## 2.基础取值筛选

In [ ]:
# 选取单列
df["question"]
# 选取多列
df[["question","answer"]]

# 条件筛选（重中之重）
df[df["category"] == "RAG"]
# 多条件筛选 & 代表且，每个条件必须括号包裹
df[(df["category"]=="RAG") & (df["answer_length"]>20)]

# 字符串包含关键词
df[df["question"].str.contains("RAG", na=False)]

## 3.文本清洗命令

In [ ]:
# 去除首尾空格
df["question"] = df["question"].str.strip()

# 字符串替换符号
df["answer"] = df["answer"].str.replace(r"[#！]", "", regex=True)

# 全部小写
df["question"] = df["question"].str.lower()

# 自定义函数批量处理数据
def clean_text(x):
    if pd.notna(x):
        return re.sub(r"\s+","",x)
    return x
df["answer"] = df["answer"].apply(clean_text)

## 4.缺失值处理

In [ ]:
# 空字符串替换为缺失值
df["question"] = df["question"].replace("", pd.NA)

# 删除【指定列存在空值】的整行
df = df.dropna(subset=["answer"])

# 空值填充
df["category"] = df["category"].fillna("未分类")

# 判断是否是空值
pd.notna(data)   # 不为空
pd.isna(data)    # 是空值

## 5.新增列、衍生计算

In [ ]:
# 新增一列：统计文本长度
df["answer_length"] = df["answer"].str.len()

## 6.分组聚合统计

In [ ]:
# 分组统计
group_df = df.groupby("category").agg(
    总数量=("doc_id","count"),
    平均长度=("answer_length","mean")
).round(2)

## 7.表格合并

In [ ]:
# 上下拼接两个DataFrame，重置行索引
full_df = pd.concat([df1, df2], ignore_index=True)

## 8.文件读写

In [ ]:
# 导出保存文件
df.to_csv("知识库.csv", index=False, encoding="utf-8-sig")

# 读取本地csv文件
df = pd.read_csv("知识库.csv", encoding="utf-8-sig")